package com.maubis.scarlet.base.support.ui


enum class ThemeColorType {
  BACKGROUND,
  STATUS_BAR,
  PRIMARY_TEXT,
  SECONDARY_TEXT,
  TERTIARY_TEXT,
  HINT_TEXT,
  DISABLED_TEXT,
  ACCENT_TEXT,
  SECTION_HEADER,
  TOOLBAR_BACKGROUND,
  TOOLBAR_ICON,
}